export const resumeLocators = {
    jobCards: '.job-roles-list-con ng-star-inserted',
    jobCardTitle: (title: string)=>`//h2[text()="${title}"]`,
    headerElement: '//div[@class="job-roles-sub-con"]//div[@class="job-roles-list-con ng-star-inserted"]//div[@class="job-role-name-con"]//h2',
    resumePage:'.job-roles-heading',
    resumeSourceDropdown: '#pr_id_5_label',
    sourceDropdownOption: (source: string) => `//ul[@id="pr_id_5_list"]//li/span[text()="${source}"]`,
    statusDropdown: '#pr_id_6_label',
    statusDropdownOption: (status: string) => `//ul[@id="pr_id_6_list"]//li/span[text()="${status}"]`,
    sortDropdown: '#pr_id_7_label',
    sortDropdownOption: (sort: string) => `//ul[@id="pr_id_7_list"]//li/span[text()="${sort}"]`,
    resumeTable: '.table-container',
    addNotes: '//h2[text()="Add a Note"]',
    enterNotes:'//div/textarea[@placeholder="Enter your note here..."]',
    saveNotesButton: (saveNotes: string)=>`//span[text()="${saveNotes}"]`,
    updateNoteMessage:'[text="Note updated successfully"]',
    deleteNotesButton:'.delete-btn',
    deleteNoteMessage: '[text="Note deleted successfully"]',
    addedNoteSection:'//div[contains(@class,"note-item ng-star-inserted")]',
    editNotesButton: '.edit-btn',
    enterUpdatedNotes:'//textarea[@placeholder="Enter your note here..."]',
    emailButton: (email: string) =>`//span[text()="${email}"]`,
    candidateDetails:'.header-container',
    tooltipButton: (button: string) => `//button[@ptooltip="${button}"]`,
    candidateForm: '//span[text()="Update Contact Info"]',
    updatedcandidateName: '#name',
    updateButton: (button1: string) => `//button[text()="${button1}"]`,
    viewResumeButton:'//a[@ptooltip="View Resume"]',
    successMessage: (message: string) => `text=${message}`,
    differentSections: (section: string) => `//div[text()="${section}"]`,
    addedQuestionrow:'user-question-row',
    resumeSummaryDetails:'.container-box',
    resumeConcernsDetails: '.gap-card mb-4',
    techSkills: (skills: string) => `//span[text()="${skills}"]`,
    chevronArrow:'.pi pi-chevron-down accordion-arrow',
    enterQuestion: '//textarea[@placeholder="Enter your question..."]',
    removedQuestion:'.technical-competence-container animated-card ng-star-inserted'
};